define([], () => {
  /**
     * Module Description...
     *
     * @type {Object} module-name
     *
     * @copyright 2021 Gateweb
     * @author Sean Lin <sean.hyl@gmail.com>
     *
     * @NApiVersion 2.1
     * @NModuleScope Public

     */
  let exports = {}
  var jkIssuedAndNotImportedSearchResults = [
    {
      internalId: { value: '291307', text: '291307' },
      mainline: ' ',
      trandate: '2021/06/01',
      subsidiary: {
        value: '4',
        text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
      },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '10', text: 'Default Tax Agency TW' },
      tranid: 'JKT-IV20210182460',
      transactionnumber: 'INV0184842',
      memomain: '',
      memo: 'VAT',
      amount: '1.181',
      fxamount: '26.00',
      grossamount: '1.181',
      netamountnotax: '1.181',
      netamount: '1.181',
      taxamount: '',
      taxtotal: '1.181',
      total: '24.074',
      department: { value: '6', text: '台中文心店' },
      createdby: { value: '11', text: 'Lanny Shieh' },
      createdfrom: '',
      class: { value: '4', text: 'B2C : Ubereat' },
      location: { value: '5', text: '台中文心店' },
      itemtype: 'TaxItem',
      linesequencenumber: '10',
      line: '12',
      item: { value: '18', text: 'TW-5%' },
      unitabbreviation: '',
      quantity: '1',
      taxcode: { value: '18', text: 'TW-5%' },
      rate: '.22711755',
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'T',
      custbody_gw_gui_not_upload: 'T',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '',
      custbody_gw_gui_num_start: 'PH39771047',
      custbody_gw_gui_num_end: 'PH39771047',
      custbody_gw_tax_id_number: '97210946',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '0',
      custbody_gw_gui_sales_amt: '504',
      custbody_gw_gui_sales_amt_tax_zero: '0',
      custbody_gw_gui_tax_amt: '26',
      custbody_gw_gui_tax_rate: '0.05',
      custbody_gw_gui_tax_type: { value: '1', text: '1-應稅' },
      custbody_gw_gui_total_amt: '530',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: {
        value: '20',
        text: '35-一般稅額電子發票[裝訂數:50張]'
      },
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '82899761',
      custbody_gw_evidence_issue_status: {
        value: '2',
        text: '憑證已開立, 未進入關網系統'
      },
      'rate.taxItem': '5.00%'
    },
    {
      internalId: { value: '291307', text: '291307' },
      mainline: ' ',
      trandate: '2021/06/01',
      subsidiary: {
        value: '4',
        text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
      },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '123', text: '42521663 Uber Protier B.V.' },
      tranid: 'JKT-IV20210182460',
      transactionnumber: 'INV0184842',
      memomain: '',
      memo: '',
      amount: '-5.723',
      fxamount: '-126.00',
      grossamount: '-5.723',
      netamountnotax: '.00',
      netamount: '.00',
      taxamount: '-.273',
      taxtotal: '1.181',
      total: '24.074',
      department: { value: '6', text: '台中文心店' },
      createdby: { value: '11', text: 'Lanny Shieh' },
      createdfrom: '',
      class: { value: '4', text: 'B2C : Ubereat' },
      location: { value: '5', text: '台中文心店' },
      itemtype: 'Discount',
      linesequencenumber: '9',
      line: '9',
      item: { value: '3758', text: 'Test - 銷售折扣4' },
      unitabbreviation: '',
      quantity: '',
      taxcode: { value: '18', text: 'TW-5%' },
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'T',
      custbody_gw_gui_not_upload: 'T',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '',
      custbody_gw_gui_num_start: 'PH39771047',
      custbody_gw_gui_num_end: 'PH39771047',
      custbody_gw_tax_id_number: '97210946',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '0',
      custbody_gw_gui_sales_amt: '504',
      custbody_gw_gui_sales_amt_tax_zero: '0',
      custbody_gw_gui_tax_amt: '26',
      custbody_gw_gui_tax_rate: '0.05',
      custbody_gw_gui_tax_type: { value: '1', text: '1-應稅' },
      custbody_gw_gui_total_amt: '530',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: {
        value: '20',
        text: '35-一般稅額電子發票[裝訂數:50張]'
      },
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '82899761',
      custbody_gw_evidence_issue_status: {
        value: '2',
        text: '憑證已開立, 未進入關網系統'
      },
      'rate.taxItem': '5.00%'
    },
    {
      internalId: { value: '291307', text: '291307' },
      mainline: ' ',
      trandate: '2021/06/01',
      subsidiary: {
        value: '4',
        text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
      },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '123', text: '42521663 Uber Protier B.V.' },
      tranid: 'JKT-IV20210182460',
      transactionnumber: 'INV0184842',
      memomain: '',
      memo: '個',
      amount: '9.539',
      fxamount: '210.00',
      grossamount: '9.539',
      netamountnotax: '3.816',
      netamount: '3.816',
      taxamount: '.50',
      taxtotal: '1.181',
      total: '24.074',
      department: { value: '6', text: '台中文心店' },
      createdby: { value: '11', text: 'Lanny Shieh' },
      createdfrom: '',
      class: { value: '4', text: 'B2C : Ubereat' },
      location: { value: '5', text: '台中文心店' },
      itemtype: 'Kit',
      linesequencenumber: '5',
      line: '5',
      item: { value: '3421', text: 'jk110cdn204 咖哩蔬菜丼' },
      unitabbreviation: '',
      quantity: '1',
      taxcode: { value: '18', text: 'TW-5%' },
      rate: '9.5389371',
      fxrate: '210.00',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'T',
      custbody_gw_gui_not_upload: 'T',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '',
      custbody_gw_gui_num_start: 'PH39771047',
      custbody_gw_gui_num_end: 'PH39771047',
      custbody_gw_tax_id_number: '97210946',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '0',
      custbody_gw_gui_sales_amt: '504',
      custbody_gw_gui_sales_amt_tax_zero: '0',
      custbody_gw_gui_tax_amt: '26',
      custbody_gw_gui_tax_rate: '0.05',
      custbody_gw_gui_tax_type: { value: '1', text: '1-應稅' },
      custbody_gw_gui_total_amt: '530',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: {
        value: '20',
        text: '35-一般稅額電子發票[裝訂數:50張]'
      },
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '82899761',
      custbody_gw_evidence_issue_status: {
        value: '2',
        text: '憑證已開立, 未進入關網系統'
      },
      'rate.taxItem': '5.00%'
    },
    {
      internalId: { value: '291307', text: '291307' },
      mainline: ' ',
      trandate: '2021/06/01',
      subsidiary: {
        value: '4',
        text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
      },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '123', text: '42521663 Uber Protier B.V.' },
      tranid: 'JKT-IV20210182460',
      transactionnumber: 'INV0184842',
      memomain: '',
      memo: '個',
      amount: '19.078',
      fxamount: '420.00',
      grossamount: '19.078',
      netamountnotax: '19.078',
      netamount: '19.078',
      taxamount: '.954',
      taxtotal: '1.181',
      total: '24.074',
      department: { value: '6', text: '台中文心店' },
      createdby: { value: '11', text: 'Lanny Shieh' },
      createdfrom: '',
      class: { value: '4', text: 'B2C : Ubereat' },
      location: { value: '5', text: '台中文心店' },
      itemtype: 'Kit',
      linesequencenumber: '1',
      line: '1',
      item: { value: '3420', text: 'jk110cdn203 咖哩雞牛丼' },
      unitabbreviation: '',
      quantity: '2',
      taxcode: { value: '18', text: 'TW-5%' },
      rate: '9.5389371',
      fxrate: '210.00',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'T',
      custbody_gw_gui_not_upload: 'T',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '',
      custbody_gw_gui_num_start: 'PH39771047',
      custbody_gw_gui_num_end: 'PH39771047',
      custbody_gw_tax_id_number: '97210946',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '0',
      custbody_gw_gui_sales_amt: '504',
      custbody_gw_gui_sales_amt_tax_zero: '0',
      custbody_gw_gui_tax_amt: '26',
      custbody_gw_gui_tax_rate: '0.05',
      custbody_gw_gui_tax_type: { value: '1', text: '1-應稅' },
      custbody_gw_gui_total_amt: '530',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: {
        value: '20',
        text: '35-一般稅額電子發票[裝訂數:50張]'
      },
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '82899761',
      custbody_gw_evidence_issue_status: {
        value: '2',
        text: '憑證已開立, 未進入關網系統'
      },
      'rate.taxItem': '5.00%'
    },
    {
      internalId: { value: '291307', text: '291307' },
      mainline: '*',
      trandate: '2021/06/01',
      subsidiary: {
        value: '4',
        text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
      },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '123', text: '42521663 Uber Protier B.V.' },
      tranid: 'JKT-IV20210182460',
      transactionnumber: 'INV0184842',
      memomain: '',
      memo: '',
      amount: '24.074',
      fxamount: '530.00',
      grossamount: '24.074',
      netamountnotax: '22.893',
      netamount: '24.074',
      taxamount: '',
      taxtotal: '1.181',
      total: '24.074',
      department: { value: '6', text: '台中文心店' },
      createdby: { value: '11', text: 'Lanny Shieh' },
      createdfrom: '',
      class: { value: '4', text: 'B2C : Ubereat' },
      location: { value: '5', text: '台中文心店' },
      itemtype: '',
      linesequencenumber: '0',
      line: '0',
      item: '',
      unitabbreviation: '',
      quantity: '',
      taxcode: '',
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'T',
      custbody_gw_gui_not_upload: 'T',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '',
      custbody_gw_gui_num_start: 'PH39771047',
      custbody_gw_gui_num_end: 'PH39771047',
      custbody_gw_tax_id_number: '97210946',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '0',
      custbody_gw_gui_sales_amt: '504',
      custbody_gw_gui_sales_amt_tax_zero: '0',
      custbody_gw_gui_tax_amt: '26',
      custbody_gw_gui_tax_rate: '0.05',
      custbody_gw_gui_tax_type: { value: '1', text: '1-應稅' },
      custbody_gw_gui_total_amt: '530',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: {
        value: '20',
        text: '35-一般稅額電子發票[裝訂數:50張]'
      },
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '82899761',
      custbody_gw_evidence_issue_status: {
        value: '2',
        text: '憑證已開立, 未進入關網系統'
      },
      'rate.taxItem': ''
    }
  ]

  var jkIssuedAndNotImportedInvObj = {
    internalId: {
      value: 291307,
      text: 291307
    },
    mainline: '*',
    trandate: '2021/06/01',
    subsidiary: {
      value: 4,
      text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
    },
    type: {
      value: 'CustInvc',
      text: 'Invoice'
    },
    entity: {
      value: 123,
      text: '42521663 Uber Protier B.V.'
    },
    tranid: 'JKT-IV20210182460',
    transactionnumber: 'INV0184842',
    memomain: '',
    memo: '',
    amount: 24.074,
    fxamount: 530,
    grossamount: 24.074,
    netamountnotax: 22.893,
    netamount: 24.074,
    taxamount: '',
    taxtotal: 1.181,
    total: 24.074,
    department: {
      value: 6,
      text: '台中文心店'
    },
    createdby: {
      value: 11,
      text: 'Lanny Shieh'
    },
    createdfrom: '',
    class: {
      value: 4,
      text: 'B2C : Ubereat'
    },
    location: {
      value: 5,
      text: '台中文心店'
    },
    itemtype: '',
    linesequencenumber: 0,
    line: 0,
    item: '',
    unitabbreviation: '',
    quantity: '',
    taxcode: '',
    rate: '',
    fxrate: '',
    custcol_gw_item_unit_amt_inc_tax: '',
    custcol_gw_item_memo: '',
    custbody_gw_gui_date: '',
    custbody_gw_gui_tax_file_date: '',
    custbody_gw_lock_transaction: 'T',
    custbody_gw_gui_not_upload: 'T',
    custbody_gw_is_issue_egui: 'T',
    custbody_gw_allowance_num_start: '',
    custbody_gw_allowance_num_end: '',
    custbody_gw_customs_export_no: '',
    custbody_gw_customs_export_category: '',
    custbody_gw_gui_address: '',
    custbody_gw_gui_title: '',
    custbody_gw_gui_num_start: 'PH39771047',
    custbody_gw_gui_num_end: 'PH39771047',
    custbody_gw_tax_id_number: 97210946,
    custbody_gw_customs_export_date: '',
    custbody_gw_egui_clearance_mark: '',
    custbody_gw_applicable_zero_tax: '',
    custbody_gw_gui_main_memo: '',
    custbody_gw_gui_sales_amt_tax_exempt: 0,
    custbody_gw_gui_sales_amt: 504,
    custbody_gw_gui_sales_amt_tax_zero: 0,
    custbody_gw_gui_tax_amt: 26,
    custbody_gw_gui_tax_rate: 0.05,
    custbody_gw_gui_tax_type: {
      value: 1,
      text: '1-應稅'
    },
    custbody_gw_gui_total_amt: 530,
    custbody_gw_creditmemo_deduction_list: '',
    custbody_gw_gui_donation_code: '',
    custbody_gw_gui_donation_mark: 'F',
    custbody_gw_gui_carrier_type: '',
    custbody_gw_gui_carrier_id_1: '',
    custbody_gw_gui_carrier_id_2: '',
    custbody_gw_gui_apply_period: '',
    custbody_gw_gui_format: {
      value: 20,
      text: '35-一般稅額電子發票[裝訂數:50張]'
    },
    custbody_gw_gui_class: '',
    custbody_gw_gui_department: '',
    statusref: {
      value: 'open',
      text: 'Open'
    },
    custbody_gw_seller_tax_id: 82899761,
    custbody_gw_evidence_issue_status: {
      value: 2,
      text: '憑證已開立, 未進入關網系統'
    },
    'rate.taxItem': '',
    lines: [
      {
        internalId: {
          value: 291307,
          text: 291307
        },
        mainline: ' ',
        trandate: '2021/06/01',
        subsidiary: {
          value: 4,
          text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
        },
        type: {
          value: 'CustInvc',
          text: 'Invoice'
        },
        entity: {
          value: 123,
          text: '42521663 Uber Protier B.V.'
        },
        tranid: 'JKT-IV20210182460',
        transactionnumber: 'INV0184842',
        memomain: '',
        memo: '',
        amount: -5.723,
        fxamount: -126,
        grossamount: -5.723,
        netamountnotax: '.00',
        netamount: '.00',
        taxamount: '-.273',
        taxtotal: 1.181,
        total: 24.074,
        department: {
          value: 6,
          text: '台中文心店'
        },
        createdby: {
          value: 11,
          text: 'Lanny Shieh'
        },
        createdfrom: '',
        class: {
          value: 4,
          text: 'B2C : Ubereat'
        },
        location: {
          value: 5,
          text: '台中文心店'
        },
        itemtype: 'Discount',
        linesequencenumber: 9,
        line: 9,
        item: {
          value: 3758,
          text: 'Test - 銷售折扣4'
        },
        unitabbreviation: '',
        quantity: '',
        taxcode: {
          value: 18,
          text: 'TW-5%'
        },
        rate: '',
        fxrate: '',
        custcol_gw_item_unit_amt_inc_tax: '',
        custcol_gw_item_memo: '',
        custbody_gw_gui_date: '',
        custbody_gw_gui_tax_file_date: '',
        custbody_gw_lock_transaction: 'T',
        custbody_gw_gui_not_upload: 'T',
        custbody_gw_is_issue_egui: 'T',
        custbody_gw_allowance_num_start: '',
        custbody_gw_allowance_num_end: '',
        custbody_gw_customs_export_no: '',
        custbody_gw_customs_export_category: '',
        custbody_gw_gui_address: '',
        custbody_gw_gui_title: '',
        custbody_gw_gui_num_start: 'PH39771047',
        custbody_gw_gui_num_end: 'PH39771047',
        custbody_gw_tax_id_number: 97210946,
        custbody_gw_customs_export_date: '',
        custbody_gw_egui_clearance_mark: '',
        custbody_gw_applicable_zero_tax: '',
        custbody_gw_gui_main_memo: '',
        custbody_gw_gui_sales_amt_tax_exempt: 0,
        custbody_gw_gui_sales_amt: 504,
        custbody_gw_gui_sales_amt_tax_zero: 0,
        custbody_gw_gui_tax_amt: 26,
        custbody_gw_gui_tax_rate: 0.05,
        custbody_gw_gui_tax_type: {
          value: 1,
          text: '1-應稅'
        },
        custbody_gw_gui_total_amt: 530,
        custbody_gw_creditmemo_deduction_list: '',
        custbody_gw_gui_donation_code: '',
        custbody_gw_gui_donation_mark: 'F',
        custbody_gw_gui_carrier_type: '',
        custbody_gw_gui_carrier_id_1: '',
        custbody_gw_gui_carrier_id_2: '',
        custbody_gw_gui_apply_period: '',
        custbody_gw_gui_format: {
          value: 20,
          text: '35-一般稅額電子發票[裝訂數:50張]'
        },
        custbody_gw_gui_class: '',
        custbody_gw_gui_department: '',
        statusref: {
          value: 'open',
          text: 'Open'
        },
        custbody_gw_seller_tax_id: 82899761,
        custbody_gw_evidence_issue_status: {
          value: 2,
          text: '憑證已開立, 未進入關網系統'
        },
        'rate.taxItem': '5.00%'
      },
      {
        internalId: {
          value: 291307,
          text: 291307
        },
        mainline: ' ',
        trandate: '2021/06/01',
        subsidiary: {
          value: 4,
          text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
        },
        type: {
          value: 'CustInvc',
          text: 'Invoice'
        },
        entity: {
          value: 123,
          text: '42521663 Uber Protier B.V.'
        },
        tranid: 'JKT-IV20210182460',
        transactionnumber: 'INV0184842',
        memomain: '',
        memo: '個',
        amount: 9.539,
        fxamount: 210,
        grossamount: 9.539,
        netamountnotax: 3.816,
        netamount: 3.816,
        taxamount: '.50',
        taxtotal: 1.181,
        total: 24.074,
        department: {
          value: 6,
          text: '台中文心店'
        },
        createdby: {
          value: 11,
          text: 'Lanny Shieh'
        },
        createdfrom: '',
        class: {
          value: 4,
          text: 'B2C : Ubereat'
        },
        location: {
          value: 5,
          text: '台中文心店'
        },
        itemtype: 'Kit',
        linesequencenumber: 5,
        line: 5,
        item: {
          value: 3421,
          text: 'jk110cdn204 咖哩蔬菜丼'
        },
        unitabbreviation: '',
        quantity: 1,
        taxcode: {
          value: 18,
          text: 'TW-5%'
        },
        rate: 9.5389371,
        fxrate: 210,
        custcol_gw_item_unit_amt_inc_tax: '',
        custcol_gw_item_memo: '',
        custbody_gw_gui_date: '',
        custbody_gw_gui_tax_file_date: '',
        custbody_gw_lock_transaction: 'T',
        custbody_gw_gui_not_upload: 'T',
        custbody_gw_is_issue_egui: 'T',
        custbody_gw_allowance_num_start: '',
        custbody_gw_allowance_num_end: '',
        custbody_gw_customs_export_no: '',
        custbody_gw_customs_export_category: '',
        custbody_gw_gui_address: '',
        custbody_gw_gui_title: '',
        custbody_gw_gui_num_start: 'PH39771047',
        custbody_gw_gui_num_end: 'PH39771047',
        custbody_gw_tax_id_number: 97210946,
        custbody_gw_customs_export_date: '',
        custbody_gw_egui_clearance_mark: '',
        custbody_gw_applicable_zero_tax: '',
        custbody_gw_gui_main_memo: '',
        custbody_gw_gui_sales_amt_tax_exempt: 0,
        custbody_gw_gui_sales_amt: 504,
        custbody_gw_gui_sales_amt_tax_zero: 0,
        custbody_gw_gui_tax_amt: 26,
        custbody_gw_gui_tax_rate: 0.05,
        custbody_gw_gui_tax_type: {
          value: 1,
          text: '1-應稅'
        },
        custbody_gw_gui_total_amt: 530,
        custbody_gw_creditmemo_deduction_list: '',
        custbody_gw_gui_donation_code: '',
        custbody_gw_gui_donation_mark: 'F',
        custbody_gw_gui_carrier_type: '',
        custbody_gw_gui_carrier_id_1: '',
        custbody_gw_gui_carrier_id_2: '',
        custbody_gw_gui_apply_period: '',
        custbody_gw_gui_format: {
          value: 20,
          text: '35-一般稅額電子發票[裝訂數:50張]'
        },
        custbody_gw_gui_class: '',
        custbody_gw_gui_department: '',
        statusref: {
          value: 'open',
          text: 'Open'
        },
        custbody_gw_seller_tax_id: 82899761,
        custbody_gw_evidence_issue_status: {
          value: 2,
          text: '憑證已開立, 未進入關網系統'
        },
        'rate.taxItem': '5.00%'
      },
      {
        internalId: {
          value: 291307,
          text: 291307
        },
        mainline: ' ',
        trandate: '2021/06/01',
        subsidiary: {
          value: 4,
          text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
        },
        type: {
          value: 'CustInvc',
          text: 'Invoice'
        },
        entity: {
          value: 123,
          text: '42521663 Uber Protier B.V.'
        },
        tranid: 'JKT-IV20210182460',
        transactionnumber: 'INV0184842',
        memomain: '',
        memo: '個',
        amount: 19.078,
        fxamount: 420,
        grossamount: 19.078,
        netamountnotax: 19.078,
        netamount: 19.078,
        taxamount: '.954',
        taxtotal: 1.181,
        total: 24.074,
        department: {
          value: 6,
          text: '台中文心店'
        },
        createdby: {
          value: 11,
          text: 'Lanny Shieh'
        },
        createdfrom: '',
        class: {
          value: 4,
          text: 'B2C : Ubereat'
        },
        location: {
          value: 5,
          text: '台中文心店'
        },
        itemtype: 'Kit',
        linesequencenumber: 1,
        line: 1,
        item: {
          value: 3420,
          text: 'jk110cdn203 咖哩雞牛丼'
        },
        unitabbreviation: '',
        quantity: 2,
        taxcode: {
          value: 18,
          text: 'TW-5%'
        },
        rate: 9.5389371,
        fxrate: 210,
        custcol_gw_item_unit_amt_inc_tax: '',
        custcol_gw_item_memo: '',
        custbody_gw_gui_date: '',
        custbody_gw_gui_tax_file_date: '',
        custbody_gw_lock_transaction: 'T',
        custbody_gw_gui_not_upload: 'T',
        custbody_gw_is_issue_egui: 'T',
        custbody_gw_allowance_num_start: '',
        custbody_gw_allowance_num_end: '',
        custbody_gw_customs_export_no: '',
        custbody_gw_customs_export_category: '',
        custbody_gw_gui_address: '',
        custbody_gw_gui_title: '',
        custbody_gw_gui_num_start: 'PH39771047',
        custbody_gw_gui_num_end: 'PH39771047',
        custbody_gw_tax_id_number: 97210946,
        custbody_gw_customs_export_date: '',
        custbody_gw_egui_clearance_mark: '',
        custbody_gw_applicable_zero_tax: '',
        custbody_gw_gui_main_memo: '',
        custbody_gw_gui_sales_amt_tax_exempt: 0,
        custbody_gw_gui_sales_amt: 504,
        custbody_gw_gui_sales_amt_tax_zero: 0,
        custbody_gw_gui_tax_amt: 26,
        custbody_gw_gui_tax_rate: 0.05,
        custbody_gw_gui_tax_type: {
          value: 1,
          text: '1-應稅'
        },
        custbody_gw_gui_total_amt: 530,
        custbody_gw_creditmemo_deduction_list: '',
        custbody_gw_gui_donation_code: '',
        custbody_gw_gui_donation_mark: 'F',
        custbody_gw_gui_carrier_type: '',
        custbody_gw_gui_carrier_id_1: '',
        custbody_gw_gui_carrier_id_2: '',
        custbody_gw_gui_apply_period: '',
        custbody_gw_gui_format: {
          value: 20,
          text: '35-一般稅額電子發票[裝訂數:50張]'
        },
        custbody_gw_gui_class: '',
        custbody_gw_gui_department: '',
        statusref: {
          value: 'open',
          text: 'Open'
        },
        custbody_gw_seller_tax_id: 82899761,
        custbody_gw_evidence_issue_status: {
          value: 2,
          text: '憑證已開立, 未進入關網系統'
        },
        'rate.taxItem': '5.00%'
      }
    ],
    taxLines: [
      {
        internalId: {
          value: 291307,
          text: 291307
        },
        mainline: ' ',
        trandate: '2021/06/01',
        subsidiary: {
          value: 4,
          text: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌'
        },
        type: {
          value: 'CustInvc',
          text: 'Invoice'
        },
        entity: {
          value: 10,
          text: 'Default Tax Agency TW'
        },
        tranid: 'JKT-IV20210182460',
        transactionnumber: 'INV0184842',
        memomain: '',
        memo: 'VAT',
        amount: 1.181,
        fxamount: 26,
        grossamount: 1.181,
        netamountnotax: 1.181,
        netamount: 1.181,
        taxamount: '',
        taxtotal: 1.181,
        total: 24.074,
        department: {
          value: 6,
          text: '台中文心店'
        },
        createdby: {
          value: 11,
          text: 'Lanny Shieh'
        },
        createdfrom: '',
        class: {
          value: 4,
          text: 'B2C : Ubereat'
        },
        location: {
          value: 5,
          text: '台中文心店'
        },
        itemtype: 'TaxItem',
        linesequencenumber: 10,
        line: 12,
        item: {
          value: 18,
          text: 'TW-5%'
        },
        unitabbreviation: '',
        quantity: 1,
        taxcode: {
          value: 18,
          text: 'TW-5%'
        },
        rate: '.22711755',
        fxrate: '5.00%',
        custcol_gw_item_unit_amt_inc_tax: '',
        custcol_gw_item_memo: '',
        custbody_gw_gui_date: '',
        custbody_gw_gui_tax_file_date: '',
        custbody_gw_lock_transaction: 'T',
        custbody_gw_gui_not_upload: 'T',
        custbody_gw_is_issue_egui: 'T',
        custbody_gw_allowance_num_start: '',
        custbody_gw_allowance_num_end: '',
        custbody_gw_customs_export_no: '',
        custbody_gw_customs_export_category: '',
        custbody_gw_gui_address: '',
        custbody_gw_gui_title: '',
        custbody_gw_gui_num_start: 'PH39771047',
        custbody_gw_gui_num_end: 'PH39771047',
        custbody_gw_tax_id_number: 97210946,
        custbody_gw_customs_export_date: '',
        custbody_gw_egui_clearance_mark: '',
        custbody_gw_applicable_zero_tax: '',
        custbody_gw_gui_main_memo: '',
        custbody_gw_gui_sales_amt_tax_exempt: 0,
        custbody_gw_gui_sales_amt: 504,
        custbody_gw_gui_sales_amt_tax_zero: 0,
        custbody_gw_gui_tax_amt: 26,
        custbody_gw_gui_tax_rate: 0.05,
        custbody_gw_gui_tax_type: {
          value: 1,
          text: '1-應稅'
        },
        custbody_gw_gui_total_amt: 530,
        custbody_gw_creditmemo_deduction_list: '',
        custbody_gw_gui_donation_code: '',
        custbody_gw_gui_donation_mark: 'F',
        custbody_gw_gui_carrier_type: '',
        custbody_gw_gui_carrier_id_1: '',
        custbody_gw_gui_carrier_id_2: '',
        custbody_gw_gui_apply_period: '',
        custbody_gw_gui_format: {
          value: 20,
          text: '35-一般稅額電子發票[裝訂數:50張]'
        },
        custbody_gw_gui_class: '',
        custbody_gw_gui_department: '',
        statusref: {
          value: 'open',
          text: 'Open'
        },
        custbody_gw_seller_tax_id: 82899761,
        custbody_gw_evidence_issue_status: {
          value: 2,
          text: '憑證已開立, 未進入關網系統'
        },
        'rate.taxItem': '5.00%'
      }
    ]
  }

  var jkIssuedAndNotImportedEguiObj = {
    internalId: '291307',
    documentDate: '2021/06/01',
    tranDate: '2021/06/01',
    subsidiaryId: '4',
    subsidiaryName: 'Parent Company : Just Kitchen Holdings Corps. : 軒饌',
    tranType: 'Invoice',
    tranid: 'JKT-IV20210182460',
    tranNum: 'INV0184842',
    buyerId: '123',
    buyerTaxId: '97210946',
    buyerAddress: '',
    buyerName: '',
    guiMemo: '',
    nsSalesAmt: '22.893',
    nsTaxAmt: '1.181',
    nsTotalAmt: '24.074',
    departmentId: '',
    departmentName: '',
    classId: '',
    createdby: '11',
    guiPeriod: '',
    isTransactionLocked: 'T',
    isNotUploadEGui: 'T',
    isIssueEgui: 'T',
    allowanceNumStart: '',
    allowanceNumEnd: '',
    eguiNumStart: 'PH39771047',
    eguiNumEnd: 'PH39771047',
    eguiMainMemo: '',
    cmDeductList: '',
    isDonate: 'F',
    donationCode: '',
    carrierType: '',
    carrierId1: '',
    carrierId2: '',
    taxApplyPeriod: {
      name: '11006',
      value: '11006',
      text: '11006',
      year: '110',
      month: '6',
      id: '69'
    },
    docFormat: { value: '20', text: '35-一般稅額電子發票[裝訂數:50張]' },
    customExportNum: '',
    customExportCategory: '',
    customExportDate: '',
    clearanceMark: '',
    zeroTaxMark: '',
    sellerTaxId: '82899761',
    gwIssueStatus: { value: '2', text: '憑證已開立, 未進入關網系統' },
    sellerName: 'TestName',
    sellerAddress: 'TestAddress',
    guiType: { name: '一般税發票', value: '07', text: '一般税發票', id: '1' },
    needUploadMig: 'NONE',
    printMark: 'Y',
    documentType: 'EGUI',
    documentTime: '23:59:59',
    documentPeriod: '11006',
    taxCalculationMethod: {
      name: 'Get NetSuite Field Values',
      value: 'NETSUITE',
      text: 'Get NetSuite Field Values',
      id: '1'
    },
    documentStatus: 'VOUCHER_SUCCESS',
    documentUploadStatus: 'A',
    manualGuiNumber: 'PH39771047',
    documentNumber: 'PH39771047',
    lineSumSalesAmt: 22.894,
    lineSumTaxExemptedSalesAmt: 0,
    lineSumTaxZeroSalesAmt: 0,
    lineSumTaxAmtAmt: 3.543,
    lineSumTotalAmt: 72.22200000000001,
    taxType: {
      name: '1-應稅',
      value: '1',
      text: '應稅',
      csvValue: '應稅',
      taxCodes: { value: '18', text: 'TW-5%' },
      id: '1'
    },
    taxRate: 0.05,
    transactions: ['291307'],
    calculatedSalesAmt: 22.893,
    calculatedTaxExemptedSalesAmt: 0,
    calculatedZeroTaxSalesAmt: 0,
    calculatedTaxAmt: 1.1446500000000002,
    calculatedTotalAmt: 24.03765,
    salesAmt: 23,
    taxExemptedSalesAmt: 0,
    zeroTaxSalesAmt: 0,
    taxAmt: 1,
    totalAmt: 24,
    lines: [
      {
        itemId: '3758',
        itemName: 'Test - 銷售折扣4',
        itemDescription: '',
        unitPrice: '',
        unitPriceForeign: '',
        quantity: '',
        unit: '',
        nsAmt: '.00',
        nsTaxAmt: '1.181',
        nsTotalAmt: '24.074',
        nsLineSeq: '9',
        nsLine: '9',
        itemType: 'Discount',
        itemMemo: '',
        itemRateAfterTax: '',
        taxCode: { value: '18', text: 'TW-5%' },
        buyerTaxId: '97210946',
        tranType: 'Invoice',
        tranid: 'JKT-IV20210182460',
        tranNum: 'INV0184842',
        tranInternalId: '291307',
        taxRate: 0.05,
        taxType: {
          name: '1-應稅',
          value: '1',
          text: '應稅',
          csvValue: '應稅',
          taxCodes: { value: '18', text: 'TW-5%' },
          id: '1'
        },
        calculatedSalesAmt: 0,
        calculatedTaxAmt: 0,
        calculatedTotalAmt: 0,
        salesAmt: 0,
        taxAmt: 1.181,
        totalAmt: 24.074,
        lineSeq: 1
      },
      {
        itemId: '3421',
        itemName: 'jk110cdn204 咖哩蔬菜丼',
        itemDescription: '個',
        unitPrice: '9.5389371',
        unitPriceForeign: '210.00',
        quantity: '1',
        unit: '',
        nsAmt: '3.816',
        nsTaxAmt: '1.181',
        nsTotalAmt: '24.074',
        nsLineSeq: '5',
        nsLine: '5',
        itemType: 'Kit',
        itemMemo: '',
        itemRateAfterTax: '',
        taxCode: { value: '18', text: 'TW-5%' },
        buyerTaxId: '97210946',
        tranType: 'Invoice',
        tranid: 'JKT-IV20210182460',
        tranNum: 'INV0184842',
        tranInternalId: '291307',
        taxRate: 0.05,
        taxType: {
          name: '1-應稅',
          value: '1',
          text: '應稅',
          csvValue: '應稅',
          taxCodes: { value: '18', text: 'TW-5%' },
          id: '1'
        },
        calculatedSalesAmt: 3.816,
        calculatedTaxAmt: 0.1908,
        calculatedTotalAmt: 4.0068,
        salesAmt: 3.816,
        taxAmt: 1.181,
        totalAmt: 24.074,
        lineSeq: 2
      },
      {
        itemId: '3420',
        itemName: 'jk110cdn203 咖哩雞牛丼',
        itemDescription: '個',
        unitPrice: '9.5389371',
        unitPriceForeign: '210.00',
        quantity: '2',
        unit: '',
        nsAmt: '19.078',
        nsTaxAmt: '1.181',
        nsTotalAmt: '24.074',
        nsLineSeq: '1',
        nsLine: '1',
        itemType: 'Kit',
        itemMemo: '',
        itemRateAfterTax: '',
        taxCode: { value: '18', text: 'TW-5%' },
        buyerTaxId: '97210946',
        tranType: 'Invoice',
        tranid: 'JKT-IV20210182460',
        tranNum: 'INV0184842',
        tranInternalId: '291307',
        taxRate: 0.05,
        taxType: {
          name: '1-應稅',
          value: '1',
          text: '應稅',
          csvValue: '應稅',
          taxCodes: { value: '18', text: 'TW-5%' },
          id: '1'
        },
        calculatedSalesAmt: 19.078,
        calculatedTaxAmt: 0.9539,
        calculatedTotalAmt: 20.0319,
        salesAmt: 19.078,
        taxAmt: 1.181,
        totalAmt: 24.074,
        lineSeq: 3
      }
    ]
  }

  exports.jkIssuedAndNotImportedSearchResults = jkIssuedAndNotImportedSearchResults
  exports.jkIssuedAndNotImportedInvObj = jkIssuedAndNotImportedInvObj
  return exports
})
