define([], () => {
  /**
     * Module Description...
     *
     * @type {Object} module-name
     *
     * @copyright 2021 Gateweb
     * @author Sean Lin <sean.hyl@gmail.com>
     *
     * @NApiVersion 2.1
     * @NModuleScope Public

     */
  let exports = {}
  var shopping99_inv_1 = [
    {
      internalId: { value: '2343746', text: '2343746' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '2', text: 'Default Tax Agency TW' },
      tranid: 'IV00000056492670',
      transactionnumber: 'CUSTINVC279921',
      memomain: '',
      memo: 'VAT',
      amount: '33.00',
      fxamount: '33.00',
      grossamount: '33.00',
      netamountnotax: '33.00',
      netamount: '33.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: '',
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'TaxItem',
      linesequencenumber: '2',
      line: '3',
      item: { value: '118', text: '三收銀及電子發票' },
      unitabbreviation: '',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '5.00',
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '885521',
      custbody_gw_gui_donation_mark: 'T',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': ''
    },
    {
      internalId: { value: '2343746', text: '2343746' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '40446', text: 'MI00000000038721 王翊瑄測試' },
      tranid: 'IV00000056492670',
      transactionnumber: 'CUSTINVC279921',
      memomain: '',
      memo: '',
      amount: '666.00',
      fxamount: '666.00',
      grossamount: '666.00',
      netamountnotax: '666.00',
      netamount: '666.00',
      taxamount: '33.00',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: '',
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'InvtPart',
      linesequencenumber: '1',
      line: '1',
      item: { value: '10519', text: 'NI20200811000099' },
      unitabbreviation: '張票券',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '885521',
      custbody_gw_gui_donation_mark: 'T',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': 'sherrywang@nineder.com'
    },
    {
      internalId: { value: '2343746', text: '2343746' },
      mainline: '*',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '40446', text: 'MI00000000038721 王翊瑄測試' },
      tranid: 'IV00000056492670',
      transactionnumber: 'CUSTINVC279921',
      memomain: '',
      memo: '',
      amount: '699.00',
      fxamount: '699.00',
      grossamount: '699.00',
      netamountnotax: '666.00',
      netamount: '699.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: '',
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: '',
      linesequencenumber: '0',
      line: '0',
      item: '',
      unitabbreviation: '',
      quantity: '',
      taxcode: '',
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '885521',
      custbody_gw_gui_donation_mark: 'T',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '',
      'email.customer': 'sherrywang@nineder.com'
    }
  ]
  var shopping99_inv_2 = [
    {
      internalId: { value: '2343647', text: '2343647' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '2', text: 'Default Tax Agency TW' },
      tranid: 'IV00000056492673',
      transactionnumber: 'CUSTINVC279932',
      memomain: '',
      memo: 'VAT',
      amount: '33.00',
      fxamount: '33.00',
      grossamount: '33.00',
      netamountnotax: '33.00',
      netamount: '33.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: '',
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'TaxItem',
      linesequencenumber: '2',
      line: '3',
      item: { value: '118', text: '三收銀及電子發票' },
      unitabbreviation: '',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '5.00',
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '/V1BNTS2',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': ''
    },
    {
      internalId: { value: '2343647', text: '2343647' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '40446', text: 'MI00000000038721 王翊瑄測試' },
      tranid: 'IV00000056492673',
      transactionnumber: 'CUSTINVC279932',
      memomain: '',
      memo: '',
      amount: '666.00',
      fxamount: '666.00',
      grossamount: '666.00',
      netamountnotax: '666.00',
      netamount: '666.00',
      taxamount: '33.00',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: '',
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'InvtPart',
      linesequencenumber: '1',
      line: '1',
      item: { value: '15772', text: 'NI20201118000014' },
      unitabbreviation: '張票券',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '/V1BNTS2',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': 'sherrywang@nineder.com'
    },
    {
      internalId: { value: '2343647', text: '2343647' },
      mainline: '*',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '40446', text: 'MI00000000038721 王翊瑄測試' },
      tranid: 'IV00000056492673',
      transactionnumber: 'CUSTINVC279932',
      memomain: '',
      memo: '',
      amount: '699.00',
      fxamount: '699.00',
      grossamount: '699.00',
      netamountnotax: '666.00',
      netamount: '699.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: '',
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: '',
      linesequencenumber: '0',
      line: '0',
      item: '',
      unitabbreviation: '',
      quantity: '',
      taxcode: '',
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '/V1BNTS2',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '',
      'email.customer': 'sherrywang@nineder.com'
    }
  ]
  var shopping99_inv_3 = [
    {
      internalId: { value: '2343446', text: '2343446' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '2', text: 'Default Tax Agency TW' },
      tranid: 'IV00000056492672',
      transactionnumber: 'CUSTINVC279931',
      memomain: '',
      memo: 'VAT',
      amount: '33.00',
      fxamount: '33.00',
      grossamount: '33.00',
      netamountnotax: '33.00',
      netamount: '33.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2338542', text: 'Sales Order #SO00000000282629' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'TaxItem',
      linesequencenumber: '2',
      line: '3',
      item: { value: '118', text: '三收銀及電子發票' },
      unitabbreviation: '',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '5.00',
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': ''
    },
    {
      internalId: { value: '2343446', text: '2343446' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '253681', text: 'MI00000000100301 樂彬吳' },
      tranid: 'IV00000056492672',
      transactionnumber: 'CUSTINVC279931',
      memomain: '',
      memo: '',
      amount: '666.00',
      fxamount: '666.00',
      grossamount: '666.00',
      netamountnotax: '666.00',
      netamount: '666.00',
      taxamount: '33.00',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2338542', text: 'Sales Order #SO00000000282629' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'InvtPart',
      linesequencenumber: '1',
      line: '1',
      item: { value: '10519', text: 'NI20200811000099' },
      unitabbreviation: '張票券',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': 'a0977551558@gmail.com'
    },
    {
      internalId: { value: '2343446', text: '2343446' },
      mainline: '*',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '253681', text: 'MI00000000100301 樂彬吳' },
      tranid: 'IV00000056492672',
      transactionnumber: 'CUSTINVC279931',
      memomain: '',
      memo: '',
      amount: '699.00',
      fxamount: '699.00',
      grossamount: '699.00',
      netamountnotax: '666.00',
      netamount: '699.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2338542', text: 'Sales Order #SO00000000282629' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: '',
      linesequencenumber: '0',
      line: '0',
      item: '',
      unitabbreviation: '',
      quantity: '',
      taxcode: '',
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '',
      'email.customer': 'a0977551558@gmail.com'
    }
  ]
  var shopping99_inv_4 = [
    {
      internalId: { value: '2343347', text: '2343347' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '2', text: 'Default Tax Agency TW' },
      tranid: 'IV00000056492674',
      transactionnumber: 'CUSTINVC279933',
      memomain: '',
      memo: 'VAT',
      amount: '26.00',
      fxamount: '26.00',
      grossamount: '26.00',
      netamountnotax: '26.00',
      netamount: '26.00',
      taxamount: '',
      taxtotal: '26.00',
      total: '550.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2341342', text: 'Sales Order #SO00000000282643' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'TaxItem',
      linesequencenumber: '2',
      line: '3',
      item: { value: '118', text: '三收銀及電子發票' },
      unitabbreviation: '',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '5.00',
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '吉方整合行銷有限公司',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '54995243',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': ''
    },
    {
      internalId: { value: '2343347', text: '2343347' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '254681', text: 'MI00000000100311 明宏施' },
      tranid: 'IV00000056492674',
      transactionnumber: 'CUSTINVC279933',
      memomain: '',
      memo: '',
      amount: '524.00',
      fxamount: '524.00',
      grossamount: '524.00',
      netamountnotax: '524.00',
      netamount: '524.00',
      taxamount: '26.00',
      taxtotal: '26.00',
      total: '550.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2341342', text: 'Sales Order #SO00000000282643' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'InvtPart',
      linesequencenumber: '1',
      line: '1',
      item: { value: '14348', text: 'NI20200928000073' },
      unitabbreviation: '張票券',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '吉方整合行銷有限公司',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '54995243',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': 'minghong.tw@gmail.com'
    },
    {
      internalId: { value: '2343347', text: '2343347' },
      mainline: '*',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '254681', text: 'MI00000000100311 明宏施' },
      tranid: 'IV00000056492674',
      transactionnumber: 'CUSTINVC279933',
      memomain: '',
      memo: '',
      amount: '550.00',
      fxamount: '550.00',
      grossamount: '550.00',
      netamountnotax: '524.00',
      netamount: '550.00',
      taxamount: '',
      taxtotal: '26.00',
      total: '550.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2341342', text: 'Sales Order #SO00000000282643' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: '',
      linesequencenumber: '0',
      line: '0',
      item: '',
      unitabbreviation: '',
      quantity: '',
      taxcode: '',
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '吉方整合行銷有限公司',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '54995243',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '',
      'email.customer': 'minghong.tw@gmail.com'
    }
  ]
  var shopping99_inv_5 = [
    {
      internalId: { value: '2343346', text: '2343346' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '2', text: 'Default Tax Agency TW' },
      tranid: 'IV00000056492662',
      transactionnumber: 'CUSTINVC279923',
      memomain: '',
      memo: 'VAT',
      amount: '33.00',
      fxamount: '33.00',
      grossamount: '33.00',
      netamountnotax: '33.00',
      netamount: '33.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2342242', text: 'Sales Order #SO00000000282652' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'TaxItem',
      linesequencenumber: '2',
      line: '3',
      item: { value: '118', text: '三收銀及電子發票' },
      unitabbreviation: '',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '5.00',
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': ''
    },
    {
      internalId: { value: '2343346', text: '2343346' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '90160', text: 'MI00000000085119 韋捷黃' },
      tranid: 'IV00000056492662',
      transactionnumber: 'CUSTINVC279923',
      memomain: '',
      memo: '',
      amount: '666.00',
      fxamount: '666.00',
      grossamount: '666.00',
      netamountnotax: '666.00',
      netamount: '666.00',
      taxamount: '33.00',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2342242', text: 'Sales Order #SO00000000282652' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'InvtPart',
      linesequencenumber: '1',
      line: '1',
      item: { value: '10519', text: 'NI20200811000099' },
      unitabbreviation: '張票券',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': 'iambelle1115@gmail.com'
    },
    {
      internalId: { value: '2343346', text: '2343346' },
      mainline: '*',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '90160', text: 'MI00000000085119 韋捷黃' },
      tranid: 'IV00000056492662',
      transactionnumber: 'CUSTINVC279923',
      memomain: '',
      memo: '',
      amount: '699.00',
      fxamount: '699.00',
      grossamount: '699.00',
      netamountnotax: '666.00',
      netamount: '699.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2342242', text: 'Sales Order #SO00000000282652' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: '',
      linesequencenumber: '0',
      line: '0',
      item: '',
      unitabbreviation: '',
      quantity: '',
      taxcode: '',
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '',
      'email.customer': 'iambelle1115@gmail.com'
    }
  ]
  var shopping99_inv_6 = [
    {
      internalId: { value: '2343247', text: '2343247' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '2', text: 'Default Tax Agency TW' },
      tranid: 'IV00000056492680',
      transactionnumber: 'CUSTINVC279939',
      memomain: '',
      memo: 'VAT',
      amount: '33.00',
      fxamount: '33.00',
      grossamount: '33.00',
      netamountnotax: '33.00',
      netamount: '33.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '688.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2342742', text: 'Sales Order #SO00000000282656' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'TaxItem',
      linesequencenumber: '2',
      line: '3',
      item: { value: '118', text: '三收銀及電子發票' },
      unitabbreviation: '',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '5.00',
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': ''
    },
    {
      internalId: { value: '2343247', text: '2343247' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '255481', text: 'MI00000000100319 乃寧柯' },
      tranid: 'IV00000056492680',
      transactionnumber: 'CUSTINVC279939',
      memomain: '',
      memo: '',
      amount: '655.00',
      fxamount: '655.00',
      grossamount: '655.00',
      netamountnotax: '655.00',
      netamount: '655.00',
      taxamount: '33.00',
      taxtotal: '33.00',
      total: '688.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2342742', text: 'Sales Order #SO00000000282656' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'InvtPart',
      linesequencenumber: '1',
      line: '1',
      item: { value: '17681', text: 'NI20210208000002' },
      unitabbreviation: '張票券',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': 'kenineling@gmail.com'
    },
    {
      internalId: { value: '2343247', text: '2343247' },
      mainline: '*',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '255481', text: 'MI00000000100319 乃寧柯' },
      tranid: 'IV00000056492680',
      transactionnumber: 'CUSTINVC279939',
      memomain: '',
      memo: '',
      amount: '688.00',
      fxamount: '688.00',
      grossamount: '688.00',
      netamountnotax: '655.00',
      netamount: '688.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '688.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2342742', text: 'Sales Order #SO00000000282656' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: '',
      linesequencenumber: '0',
      line: '0',
      item: '',
      unitabbreviation: '',
      quantity: '',
      taxcode: '',
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '',
      'email.customer': 'kenineling@gmail.com'
    }
  ]
  var shopping99_inv_7 = [
    {
      internalId: { value: '2343246', text: '2343246' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '2', text: 'Default Tax Agency TW' },
      tranid: 'IV00000056492664',
      transactionnumber: 'CUSTINVC279925',
      memomain: '',
      memo: 'VAT',
      amount: '33.00',
      fxamount: '33.00',
      grossamount: '33.00',
      netamountnotax: '33.00',
      netamount: '33.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2340142', text: 'Sales Order #SO00000000282631' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'TaxItem',
      linesequencenumber: '2',
      line: '3',
      item: { value: '118', text: '三收銀及電子發票' },
      unitabbreviation: '',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '5.00',
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': ''
    },
    {
      internalId: { value: '2343246', text: '2343246' },
      mainline: ' ',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '253881', text: 'MI00000000100303 秀玲韋' },
      tranid: 'IV00000056492664',
      transactionnumber: 'CUSTINVC279925',
      memomain: '',
      memo: '',
      amount: '666.00',
      fxamount: '666.00',
      grossamount: '666.00',
      netamountnotax: '666.00',
      netamount: '666.00',
      taxamount: '33.00',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2340142', text: 'Sales Order #SO00000000282631' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: 'InvtPart',
      linesequencenumber: '1',
      line: '1',
      item: { value: '10519', text: 'NI20200811000099' },
      unitabbreviation: '張票券',
      quantity: '1',
      taxcode: { value: '118', text: '三收銀及電子發票' },
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '5.00%',
      'email.customer': 'wei0929@hotmail.com'
    },
    {
      internalId: { value: '2343246', text: '2343246' },
      mainline: '*',
      trandate: '2021-5-3',
      subsidiary: { value: '1', text: 'Group : Nineder_TW' },
      type: { value: 'CustInvc', text: 'Invoice' },
      entity: { value: '253881', text: 'MI00000000100303 秀玲韋' },
      tranid: 'IV00000056492664',
      transactionnumber: 'CUSTINVC279925',
      memomain: '',
      memo: '',
      amount: '699.00',
      fxamount: '699.00',
      grossamount: '699.00',
      netamountnotax: '666.00',
      netamount: '699.00',
      taxamount: '',
      taxtotal: '33.00',
      total: '699.00',
      department: '',
      createdby: { value: '-4', text: '-System-' },
      createdfrom: { value: '2340142', text: 'Sales Order #SO00000000282631' },
      class: '',
      location: { value: '45', text: 'Nineder(Luzhu）' },
      itemtype: '',
      linesequencenumber: '0',
      line: '0',
      item: '',
      unitabbreviation: '',
      quantity: '',
      taxcode: '',
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '0000000000',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '0000000000',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_gui_tax_rate: '',
      custbody_gw_gui_tax_type: '',
      custbody_gw_gui_total_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: { value: 'open', text: 'Open' },
      custbody_gw_seller_tax_id: '',
      custbody_gw_evidence_issue_status: '',
      'rate.taxItem': '',
      'email.customer': 'wei0929@hotmail.com'
    }
  ]
  exports.shopping99SearchResults = {
    IV00000056492670: shopping99_inv_1,
    IV00000056492673: shopping99_inv_2,
    IV00000056492672: shopping99_inv_3,
    IV00000056492674: shopping99_inv_4,
    IV00000056492662: shopping99_inv_5,
    IV00000056492680: shopping99_inv_6,
    IV00000056492664: shopping99_inv_7
  }
  return exports
})
