export const config = {
  name: 'TSTDRV2303566',
  nsAcctId: 'TSTDRV2303566',
  printBaseUrl: 'https://nsprint.tweinv.com:443',
  downloadBaseUrl: 'https://nsprint.tweinv.com:443',
  turkeyBaseUrl: 'https://sstest.gwis.com.tw:443',
  isActive: true,
  taxCalcMethod: { value: '1', text: 'Get NetSuite Field Values' },
  defaultEGuiFormat: { value: '20', text: '35-一般稅額電子發票[裝訂數:50張]' },
  defaultAllowanceFormat: {
    value: '17',
    text: '33-三聯式、電子計算機三聯式收銀機、一般稅電子發票之折讓單',
  },
  id: '3',
}
export const businessEntity = {
  name: '關網資訊',
  taxId: '24549210',
  vatId: '245492100',
  title: '關網資訊股份有限公司',
  ownerName: '林克任',
  taxFilingType: { value: '1', text: '按期申報' },
  consolidatePaymentCode: {
    name: '0-單一機構或無總繳之總分支機構',
    value: '0',
    text: '單一機構或無總繳之總分支機構',
    code: '1',
    id: '1',
  },
  isConsolidateToParent: false,
  city: { value: '1', text: '台北市' },
  address: '忠孝東路四段258號2樓',
  repName: '林克任',
  repTel: '0223131344',
  repEmail: 'jackielin@gateweb.com.tw',
  repExtension: '',
  isAppliedByAgent: false,
  agentRegisteredNum: '',
  applicantIdNum: '',
  applicantName: '',
  applicantAreaCode: '',
  applicantTel: '',
  applicantExtension: '',
  nsAccountId: '',
  subsidiary: {
    value: '3',
    text:
      'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
  },
  location: '',
  taxFilingAgent: '',
  taxDeductOption: false,
  isNonValueAdded: false,
  id: '1',
}

export const regularGuiType = {
  name: '一般税發票',
  value: '07',
  text: '一般税發票',
  id: '1',
}
export const specialGuiType = {
  name: '特種税發票',
  value: '08',
  text: '特種税發票',
  id: '2',
}
export const applyPeriod11004 = {
  name: '11004',
  value: '11004',
  text: '11004',
  year: '110',
  month: '4',
  id: '68',
}
export const docFormatDefault = {
  name: '35-一般稅額電子發票[裝訂數:50張]',
  value: '35',
  text: '一般稅額電子發票[裝訂數:50張]',
  mofCode: '07',
  id: '20',
}
export const migType = {
  name: 'Issue B2C EGUI',
  documentType: 'EGUI',
  businessTranType: 'B2C',
  migType: 'C0401',
  xmlFileName: 'gw_c0401_b2c_egui.xml.ftl',
  action: 'ISSUE',
  id: '1',
}
export const taxCalculation = {
  name: 'Get NetSuite Field Values',
  value: 'NETSUITE',
  text: 'Get NetSuite Field Values',
  id: '1',
}
export const taxableTaxType = {
  name: '1-應稅',
  value: '1',
  text: '應稅',
  csvValue: '應稅',
  taxCodes: { value: '6', text: '應稅-5%' },
  id: '1',
}

export const invoiceSearchResult = [
  {
    internalId: { value: '3', text: '3' },
    mainline: '*',
    trandate: '4/27/2021',
    subsidiary: {
      value: '3',
      text:
        'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
    },
    type: { value: 'CustInvc', text: 'Invoice' },
    entity: { value: '16', text: '3 TestCompany' },
    tranid: '1',
    transactionnumber: '1',
    memomain: '',
    memo: '',
    amount: '3118.50',
    fxamount: '3118.50',
    grossamount: '3118.50',
    netamountnotax: '2970.00',
    netamount: '3118.50',
    taxamount: '',
    taxtotal: '148.50',
    total: '3118.50',
    department: '',
    createdby: { value: '12', text: 'Sean Lin' },
    createdfrom: '',
    class: '',
    location: { value: '4', text: 'Taiwan : Taipei-Taipei' },
    itemtype: '',
    linesequencenumber: '0',
    line: '0',
    item: '',
    unitabbreviation: '',
    quantity: '',
    taxcode: '',
    rate: '',
    fxrate: '',
    custcol_gw_item_unit_amt_inc_tax: '',
    custcol_gw_item_memo: '',
    custbody_gw_gui_date: '',
    custbody_gw_gui_tax_file_date: '',
    custbody_gw_lock_transaction: 'F',
    custbody_gw_gui_not_upload: 'F',
    custbody_gw_is_issue_egui: 'T',
    custbody_gw_allowance_num_start: '',
    custbody_gw_allowance_num_end: '',
    custbody_gw_customs_export_no: '',
    custbody_gw_customs_export_category: '',
    custbody_gw_gui_address: '',
    custbody_gw_gui_title: '',
    custbody_gw_gui_num_start: '',
    custbody_gw_gui_num_end: '',
    custbody_gw_tax_id_number: '24549210',
    custbody_gw_customs_export_date: '',
    custbody_gw_egui_clearance_mark: '',
    custbody_gw_applicable_zero_tax: '',
    custbody_gw_gui_main_memo: '',
    custbody_gw_gui_sales_amt_tax_exempt: '',
    custbody_gw_gui_sales_amt: '',
    custbody_gw_gui_sales_amt_tax_zero: '',
    custbody_gw_gui_tax_amt: '',
    custbody_gw_creditmemo_deduction_list: '',
    custbody_gw_gui_donation_code: '',
    custbody_gw_gui_donation_mark: 'F',
    custbody_gw_gui_carrier_type: '',
    custbody_gw_gui_carrier_id_1: '',
    custbody_gw_gui_carrier_id_2: '',
    custbody_gw_gui_apply_period: '',
    custbody_gw_gui_format: '',
    custbody_gw_gui_class: '',
    custbody_gw_gui_department: '',
    statusref: { value: 'open', text: 'Open' },
    'rate.taxItem': '',
  },
  {
    internalId: { value: '3', text: '3' },
    mainline: ' ',
    trandate: '4/27/2021',
    subsidiary: {
      value: '3',
      text:
        'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
    },
    type: { value: 'CustInvc', text: 'Invoice' },
    entity: { value: '16', text: '3 TestCompany' },
    tranid: '1',
    transactionnumber: '1',
    memomain: '',
    memo: '',
    amount: '2970.00',
    fxamount: '2970.00',
    grossamount: '2970.00',
    netamountnotax: '2970.00',
    netamount: '2970.00',
    taxamount: '148.50',
    taxtotal: '148.50',
    total: '3118.50',
    department: '',
    createdby: { value: '12', text: 'Sean Lin' },
    createdfrom: '',
    class: '',
    location: { value: '4', text: 'Taiwan : Taipei-Taipei' },
    itemtype: 'InvtPart',
    linesequencenumber: '1',
    line: '1',
    item: { value: '9', text: 'GW Test Item 1' },
    unitabbreviation: '個',
    quantity: '3',
    taxcode: { value: '6', text: '應稅-5%' },
    rate: '990.00',
    fxrate: '990.00',
    custcol_gw_item_unit_amt_inc_tax: '',
    custcol_gw_item_memo: '',
    custbody_gw_gui_date: '',
    custbody_gw_gui_tax_file_date: '',
    custbody_gw_lock_transaction: 'F',
    custbody_gw_gui_not_upload: 'F',
    custbody_gw_is_issue_egui: 'T',
    custbody_gw_allowance_num_start: '',
    custbody_gw_allowance_num_end: '',
    custbody_gw_customs_export_no: '',
    custbody_gw_customs_export_category: '',
    custbody_gw_gui_address: '',
    custbody_gw_gui_title: '',
    custbody_gw_gui_num_start: '',
    custbody_gw_gui_num_end: '',
    custbody_gw_tax_id_number: '24549210',
    custbody_gw_customs_export_date: '',
    custbody_gw_egui_clearance_mark: '',
    custbody_gw_applicable_zero_tax: '',
    custbody_gw_gui_main_memo: '',
    custbody_gw_gui_sales_amt_tax_exempt: '',
    custbody_gw_gui_sales_amt: '',
    custbody_gw_gui_sales_amt_tax_zero: '',
    custbody_gw_gui_tax_amt: '',
    custbody_gw_creditmemo_deduction_list: '',
    custbody_gw_gui_donation_code: '',
    custbody_gw_gui_donation_mark: 'F',
    custbody_gw_gui_carrier_type: '',
    custbody_gw_gui_carrier_id_1: '',
    custbody_gw_gui_carrier_id_2: '',
    custbody_gw_gui_apply_period: '',
    custbody_gw_gui_format: '',
    custbody_gw_gui_class: '',
    custbody_gw_gui_department: '',
    statusref: { value: 'open', text: 'Open' },
    'rate.taxItem': '5.00%',
  },
  {
    internalId: { value: '3', text: '3' },
    mainline: ' ',
    trandate: '4/27/2021',
    subsidiary: {
      value: '3',
      text:
        'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
    },
    type: { value: 'CustInvc', text: 'Invoice' },
    entity: {
      value: '15',
      text:
        'Default Tax Agency TW : Default Tax Agency TW (3 - GW Test Subsidiary - Taipei) (20210426-115517)',
    },
    tranid: '1',
    transactionnumber: '1',
    memomain: '',
    memo: 'VAT',
    amount: '148.50',
    fxamount: '148.50',
    grossamount: '148.50',
    netamountnotax: '148.50',
    netamount: '148.50',
    taxamount: '',
    taxtotal: '148.50',
    total: '3118.50',
    department: '',
    createdby: { value: '12', text: 'Sean Lin' },
    createdfrom: '',
    class: '',
    location: { value: '4', text: 'Taiwan : Taipei-Taipei' },
    itemtype: 'TaxItem',
    linesequencenumber: '4',
    line: '5',
    item: { value: '6', text: '應稅-5%' },
    unitabbreviation: '',
    quantity: '1',
    taxcode: { value: '6', text: '應稅-5%' },
    rate: '5.00',
    fxrate: '5.00%',
    custcol_gw_item_unit_amt_inc_tax: '',
    custcol_gw_item_memo: '',
    custbody_gw_gui_date: '',
    custbody_gw_gui_tax_file_date: '',
    custbody_gw_lock_transaction: 'F',
    custbody_gw_gui_not_upload: 'F',
    custbody_gw_is_issue_egui: 'T',
    custbody_gw_allowance_num_start: '',
    custbody_gw_allowance_num_end: '',
    custbody_gw_customs_export_no: '',
    custbody_gw_customs_export_category: '',
    custbody_gw_gui_address: '',
    custbody_gw_gui_title: '',
    custbody_gw_gui_num_start: '',
    custbody_gw_gui_num_end: '',
    custbody_gw_tax_id_number: '24549210',
    custbody_gw_customs_export_date: '',
    custbody_gw_egui_clearance_mark: '',
    custbody_gw_applicable_zero_tax: '',
    custbody_gw_gui_main_memo: '',
    custbody_gw_gui_sales_amt_tax_exempt: '',
    custbody_gw_gui_sales_amt: '',
    custbody_gw_gui_sales_amt_tax_zero: '',
    custbody_gw_gui_tax_amt: '',
    custbody_gw_creditmemo_deduction_list: '',
    custbody_gw_gui_donation_code: '',
    custbody_gw_gui_donation_mark: 'F',
    custbody_gw_gui_carrier_type: '',
    custbody_gw_gui_carrier_id_1: '',
    custbody_gw_gui_carrier_id_2: '',
    custbody_gw_gui_apply_period: '',
    custbody_gw_gui_format: '',
    custbody_gw_gui_class: '',
    custbody_gw_gui_department: '',
    statusref: { value: 'open', text: 'Open' },
    'rate.taxItem': '5.00%',
  },
]

export const invoice = {
  internalId: { value: '3', text: '3' },
  mainline: '*',
  trandate: '4/27/2021',
  subsidiary: {
    value: '3',
    text:
      'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
  },
  type: {
    value: 'CustInvc',
    text: 'Invoice',
  },
  entity: {
    value: '16',
    text: '3 TestCompany',
  },
  tranid: '1',
  transactionnumber: '1',
  memomain: '',
  memo: '',
  amount: '3118.50',
  fxamount: '3118.50',
  grossamount: '3118.50',
  netamountnotax: '2970.00',
  netamount: '3118.50',
  taxamount: '',
  taxtotal: '148.50',
  total: '3118.50',
  department: '',
  createdby: {
    value: '12',
    text: 'Sean Lin',
  },
  createdfrom: '',
  class: '',
  location: {
    value: '4',
    text: 'Taiwan : Taipei-Taipei',
  },
  itemtype: '',
  linesequencenumber: '0',
  line: '0',
  item: '',
  unitabbreviation: '',
  quantity: '',
  taxcode: '',
  rate: '',
  fxrate: '',
  custcol_gw_item_unit_amt_inc_tax: '',
  custcol_gw_item_memo: '',
  custbody_gw_gui_date: '',
  custbody_gw_gui_tax_file_date: '',
  custbody_gw_lock_transaction: 'F',
  custbody_gw_gui_not_upload: 'F',
  custbody_gw_is_issue_egui: 'T',
  custbody_gw_allowance_num_start: '',
  custbody_gw_allowance_num_end: '',
  custbody_gw_customs_export_no: '',
  custbody_gw_customs_export_category: '',
  custbody_gw_gui_address: '',
  custbody_gw_gui_title: '',
  custbody_gw_gui_num_start: '',
  custbody_gw_gui_num_end: '',
  custbody_gw_tax_id_number: '24549210',
  custbody_gw_customs_export_date: '',
  custbody_gw_egui_clearance_mark: '',
  custbody_gw_applicable_zero_tax: '',
  custbody_gw_gui_main_memo: '',
  custbody_gw_gui_sales_amt_tax_exempt: '',
  custbody_gw_gui_sales_amt: '',
  custbody_gw_gui_sales_amt_tax_zero: '',
  custbody_gw_gui_tax_amt: '',
  custbody_gw_creditmemo_deduction_list: '',
  custbody_gw_gui_donation_code: '',
  custbody_gw_gui_donation_mark: 'F',
  custbody_gw_gui_carrier_type: '',
  custbody_gw_gui_carrier_id_1: '',
  custbody_gw_gui_carrier_id_2: '',
  custbody_gw_gui_apply_period: '',
  custbody_gw_gui_format: '',
  custbody_gw_gui_class: '',
  custbody_gw_gui_department: '',
  statusref: {
    value: 'open',
    text: 'Open',
  },
  'rate.taxItem': '',
  lines: [
    {
      internalId: { value: '3', text: '3' },
      mainline: ' ',
      trandate: '4/27/2021',
      subsidiary: {
        value: '3',
        text:
          'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
      },
      type: {
        value: 'CustInvc',
        text: 'Invoice',
      },
      entity: {
        value: '16',
        text: '3 TestCompany',
      },
      tranid: '1',
      transactionnumber: '1',
      memomain: '',
      memo: '',
      amount: '2970.00',
      fxamount: '2970.00',
      grossamount: '2970.00',
      netamountnotax: '2970.00',
      netamount: '2970.00',
      taxamount: '148.50',
      taxtotal: '148.50',
      total: '3118.50',
      department: '',
      createdby: {
        value: '12',
        text: 'Sean Lin',
      },
      createdfrom: '',
      class: '',
      location: {
        value: '4',
        text: 'Taiwan : Taipei-Taipei',
      },
      itemtype: 'InvtPart',
      linesequencenumber: '1',
      line: '1',
      item: {
        value: '9',
        text: 'GW Test Item 1',
      },
      unitabbreviation: '個',
      quantity: '3',
      taxcode: {
        value: '6',
        text: '應稅-5%',
      },
      rate: '990.00',
      fxrate: '990.00',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '24549210',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: {
        value: 'open',
        text: 'Open',
      },
      'rate.taxItem': '5.00%',
    },
  ],
  taxLines: [
    {
      internalId: { value: '3', text: '3' },
      mainline: ' ',
      trandate: '4/27/2021',
      subsidiary: {
        value: '3',
        text:
          'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
      },
      type: {
        value: 'CustInvc',
        text: 'Invoice',
      },
      entity: {
        value: '15',
        text:
          'Default Tax Agency TW : Default Tax Agency TW (3 - GW Test Subsidiary - Taipei) (20210426-115517)',
      },
      tranid: '1',
      transactionnumber: '1',
      memomain: '',
      memo: 'VAT',
      amount: '148.50',
      fxamount: '148.50',
      grossamount: '148.50',
      netamountnotax: '148.50',
      netamount: '148.50',
      taxamount: '',
      taxtotal: '148.50',
      total: '3118.50',
      department: '',
      createdby: {
        value: '12',
        text: 'Sean Lin',
      },
      createdfrom: '',
      class: '',
      location: {
        value: '4',
        text: 'Taiwan : Taipei-Taipei',
      },
      itemtype: 'TaxItem',
      linesequencenumber: '4',
      line: '5',
      item: {
        value: '6',
        text: '應稅-5%',
      },
      unitabbreviation: '',
      quantity: '1',
      taxcode: {
        value: '6',
        text: '應稅-5%',
      },
      rate: '5.00',
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: '',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: '24549210',
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: {
        value: 'open',
        text: 'Open',
      },
      'rate.taxItem': '5.00%',
    },
  ],
}

export const egui = {
  internalId: '3',
  documentDate: '4/27/2021',
  tranDate: '4/27/2021',
  subsidiaryId: '3',
  subsidiaryName:
    'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
  tranType: 'Invoice',
  tranid: '1',
  tranNum: '1',
  buyerId: '16',
  buyerTaxId: '24549210',
  buyerAddress: '',
  buyerTitle: '',
  guiMemo: '',
  nsSalesAmt: '2970.00',
  nsTaxAmt: '148.50',
  nsTotalAmt: '3118.50',
  departmentId: '',
  departmentName: '',
  classId: '',
  createdby: '12',
  guiTaxFileDate: '',
  isTransactionLocked: 'F',
  isNotUploadEGui: 'F',
  isIssueEgui: 'T',
  allowanceNumStart: '',
  allowanceNumEnd: '',
  eguiNumStart: '',
  eguiNumEnd: '',
  eguiMainMemo: '',
  cmDeductList: '',
  isDonate: 'F',
  donationCode: '',
  carrierType: '',
  carrierId1: '',
  carrierId2: '',
  taxApplyPeriod: {
    name: '11004',
    value: '11004',
    text: '11004',
    year: '110',
    month: '4',
    id: '68',
  },
  docFormat: {
    name: '35-一般稅額電子發票[裝訂數:50張]',
    value: '35',
    text: '一般稅額電子發票[裝訂數:50張]',
    mofCode: '07',
    id: '20',
  },
  customExportNum: '',
  customExportCategory: '',
  customExportDate: '',
  clearanceMark: '',
  zeroTaxMark: '',
  sellerTaxId: '24549210',
  sellerName: '關網資訊股份有限公司',
  sellerAddress: '台北市忠孝東路四段258號2樓',
  documentType: 'EGUI',
  documentTime: '23:59:59',
  guiType: { name: '一般税發票', value: '07', text: '一般税發票', id: '1' },
  documentPeriod: '11004',
  taxCalculationMethod: {
    name: 'Get NetSuite Field Values',
    value: 'NETSUITE',
    text: 'Get NetSuite Field Values',
    id: '1',
  },
  migType: {
    name: 'Issue B2C EGUI',
    documentType: 'EGUI',
    businessTranType: 'B2C',
    migType: 'C0401',
    xmlFileName: 'gw_c0401_b2c_egui.xml.ftl',
    action: 'ISSUE',
    id: '1',
  },
  documentStatus: 'VOUCHER_ISSUE',
  documentUploadStatus: 'A',
  needUploadMig: 'ALL',
  printMark: 'Y',
  lineSumSalesAmt: 2970,
  lineSumTaxExemptedSalesAmt: 0,
  lineSumTaxZeroSalesAmt: 0,
  lineSumTaxAmtAmt: 148.5,
  lineSumTotalAmt: 3118.5,
  taxType: {
    name: '1-應稅',
    value: '1',
    text: '應稅',
    csvValue: '應稅',
    taxCodes: { value: '6', text: '應稅-5%' },
    id: '1',
  },
  taxRate: 0.05,
  calculatedSalesAmt: 2970,
  calculatedTaxExemptedSalesAmt: 0,
  calculatedZeroTaxSalesAmt: 0,
  calculatedTaxAmt: 148.5,
  calculatedTotalAmt: 3118.5,
  salesAmt: 2970,
  taxExemptedSalesAmt: 0,
  zeroTaxSalesAmt: 0,
  taxAmt: 149,
  totalAmt: 3119,
  lines: [
    {
      itemId: '9',
      itemName: 'GW Test Item 1',
      itemDescription: '',
      unitPrice: '990.00',
      unitPriceForeign: '990.00',
      quantity: '3',
      unit: '個',
      nsAmt: '2970.00',
      nsTaxAmt: '148.50',
      nsTotalAmt: '3118.50',
      nsLineSeq: '1',
      nsLine: '1',
      itemType: 'InvtPart',
      itemMemo: '',
      itemRateAfterTax: '',
      taxCode: { value: '6', text: '應稅-5%' },
      buyerTaxId: '24549210',
      tranType: 'Invoice',
      tranid: '1',
      tranNum: '1',
      tranInternalId: '3',
      taxRate: 0.05,
      taxType: {
        name: '1-應稅',
        value: '1',
        text: '應稅',
        csvValue: '應稅',
        taxCodes: { value: '6', text: '應稅-5%' },
        id: '1',
      },
      calculatedSalesAmt: 2970,
      calculatedTaxAmt: 148.5,
      calculatedTotalAmt: 3118.5,
      salesAmt: 2970,
      taxAmt: 148.5,
      totalAmt: 3118.5,
      lineSeq: 1,
    },
  ],
}
