require(['SuiteApps/com.gateweb.gwegui/gw_issue_egui_job/gw_repo_voucher'], (
  gwVoucherRepo
) => {
  var eguiObj = {
    documentDate: '4/27/2021',
    tranDate: '4/27/2021',
    subsidiaryId: '3',
    subsidiaryName:
      'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
    tranType: 'Invoice',
    tranid: '1',
    tranNum: '1',
    buyerId: '16',
    buyerTaxId: '24549210',
    buyerAddress: '',
    buyerTitle: '',
    guiMemo: '',
    nsSalesAmt: '2970.00',
    nsTaxAmt: '148.50',
    nsTotalAmt: '3118.50',
    departmentId: '',
    departmentName: '',
    classId: '',
    createdby: '12',
    guiTaxFileDate: '',
    isTransactionLocked: 'F',
    isUploadEGui: 'F',
    isIssueEgui: 'T',
    allowanceNumStart: '',
    allowanceNumEnd: '',
    eguiNumStart: '',
    eguiNumEnd: '',
    eguiMainMemo: '',
    cmDeductList: '',
    isDonate: 'F',
    donationCode: '',
    carrierType: '',
    carrierId1: '',
    carrierId2: '',
    taxApplyPeriod: {
      name: '11004',
      value: '11004',
      text: '11004',
      year: '110',
      month: '4',
      id: '68',
    },
    docFormat: {
      name: '35-一般稅額電子發票[裝訂數:50張]',
      value: '35',
      text: '一般稅額電子發票[裝訂數:50張]',
      mofCode: '07',
      id: '20',
    },
    customExportNum: '',
    customExportCategory: '',
    customExportDate: '',
    clearanceMark: '',
    zeroTaxMark: '',
    sellerTaxId: '24549210',
    sellerName: '關網資訊股份有限公司',
    sellerAddress: '台北市忠孝東路四段258號2樓',
    documentType: 'EGUI',
    documentTime: '23:59:59',
    documentPeriod: '11004',
    taxCalculationMethod: {
      name: 'Get NetSuite Field Values',
      value: 'NETSUITE',
      text: 'Get NetSuite Field Values',
      id: '1',
    },
    lineSumSalesAmt: 2970,
    lineSumTaxExemptedSalesAmt: 0,
    lineSumTaxZeroSalesAmt: 0,
    lineSumTaxAmtAmt: 148.5,
    lineSumTotalAmt: 3118.5,
    taxType: {
      name: '1-應稅',
      value: '1',
      text: '應稅',
      csvValue: '應稅',
      taxCodes: {
        value: '6',
        text: '應稅-5%',
      },
      id: '1',
    },
    taxRate: 0.05,
    calculatedSalesAmt: 2970,
    calculatedTaxExemptedSalesAmt: 0,
    calculatedZeroTaxSalesAmt: 0,
    calculatedTaxAmt: 148.5,
    calculatedTotalAmt: 3118.5,
    salesAmt: 2970,
    taxExemptedSalesAmt: 0,
    zeroTaxSalesAmt: 0,
    taxAmt: 149,
    totalAmt: 3119,
    lines: [
      {
        itemId: '9',
        itemName: 'GW Test Item 1',
        itemDescription: '',
        unitPrice: '990.00',
        unitPriceForeign: '990.00',
        quantity: '3',
        unit: '個',
        nsAmt: '2970.00',
        nsTaxAmt: '148.50',
        nsTotalAmt: '3118.50',
        nsLineSeq: '1',
        nsLine: '1',
        itemType: 'InvtPart',
        itemMemo: '',
        itemRateAfterTax: '',
        taxCode: {
          value: '6',
          text: '應稅-5%',
        },
        buyerTaxId: '24549210',
        taxRate: 0.05,
        taxType: {
          name: '1-應稅',
          value: '1',
          text: '應稅',
          csvValue: '應稅',
          taxCodes: {
            value: '6',
            text: '應稅-5%',
          },
          id: '1',
        },
        calculatedSalesAmt: 2970,
        calculatedTaxAmt: 148.5,
        calculatedTotalAmt: 3118.5,
        salesAmt: 2970,
        taxAmt: 148.5,
        totalAmt: 3118.5,
        lineSeq: 1,
      },
    ],
  }
  var voucherRepo = new gwVoucherRepo()
  var voucherMain = voucherRepo.transEGuiToVoucherMain(eguiObj)
  log.debug({ title: 'voucherMain', details: voucherMain })
  var voucherDetails = voucherRepo.transEguiDetailToVoucherDetail(eguiObj.lines)
  log.debug({ title: 'voucherDetails', details: voucherDetails })
  log.debug({ title: 'Execution end' })
})
