require([
  'SuiteApps/com.gateweb.gwegui/gw_issue_egui_job/gw_egui_book_service'
], (gwEguiBookService) => {
  var eguiObj = {
    internalId: 3661843,
    documentDate: '2021-12-2',
    tranDate: '2021-12-2',
    subsidiaryId: 23,
    subsidiaryName: 'Group : Nineder_TW : 純萃自然股份有限公司',
    tranType: 'Invoice',
    tranid: 'IV00000056569294',
    tranNum: 'CUSTINVC365490',
    guiDate: '',
    buyerId: 713659,
    buyerTaxId: 24549210,
    buyerAddress: '00000000000',
    buyerName: '00000000000',
    buyerEmail: 'jackielin@gateweb.com.tw',
    guiMemo: '',
    nsSalesAmt: 1004,
    nsSalesAmtTaxZero: '',
    nsSalesAmtTaxExempt: '',
    nsTaxAmt: 50,
    nsTotalAmt: 1054,
    taxType: {
      name: '1-應稅',
      value: '1',
      text: '應稅',
      csvValue: '應稅',
      taxCodes: { value: '118', text: '三收銀及電子發票' },
      id: '1'
    },
    salesAmt: 1004,
    taxExemptedSalesAmt: 0,
    zeroTaxSalesAmt: 0,
    taxAmt: 50,
    totalAmt: 1054,
    taxRate: 0.05,
    departmentId: '',
    departmentName: '',
    classId: '',
    createdby: 434109,
    guiPeriod: '',
    isTransactionLocked: 'T',
    isNotUploadEGui: 'T',
    isIssueEgui: 'T',
    allowanceNumStart: '',
    allowanceNumEnd: '',
    eguiNumStart: 'QN68800203',
    eguiNumEnd: 'QN68800203',
    eguiMainMemo: '',
    cmDeductList: '',
    isDonate: 'F',
    donationCode: '',
    carrierType: '',
    carrierId1: '',
    carrierId2: '',
    taxApplyPeriod: {
      name: '11012',
      value: '11012',
      text: '11012',
      year: '110',
      month: '12',
      id: '72'
    },
    docFormat: {
      name: '35-一般稅額電子發票[裝訂數:50張]',
      value: '35',
      text: '一般稅額電子發票[裝訂數:50張]',
      mofCode: '07',
      id: '20'
    },
    customExportNum: '',
    customExportCategory: '',
    customExportDate: '',
    clearanceMark: '',
    zeroTaxMark: '',
    sellerProfile: '',
    sellerTaxId: '50875956',
    sellerAddress: '台北市大安區仁愛路3段82之2號3樓',
    sellerName: '純萃自然股份有限公司',
    gwIssueStatus: { value: 2, text: '憑證已開立, 未進入關網系統' },
    guiType: { name: '一般税發票', value: '07', text: '一般税發票', id: '1' },
    needUploadMig: 'NONE',
    printMark: 'Y',
    documentType: 'EGUI',
    documentTime: '23:59:59',
    documentPeriod: '11012',
    taxCalculationMethod: {
      name: 'Get NetSuite Field Values',
      value: 'NETSUITE',
      text: 'Get NetSuite Field Values',
      id: '1'
    },
    documentStatus: 'VOUCHER_SUCCESS',
    documentUploadStatus: 'A',
    manualGuiNumber: 'QN68800203',
    documentNumber: 'QN68800203',
    transactions: [3661843],
    lines: [
      {
        itemId: 1143,
        itemName: '商品一批(銷售)',
        itemDescription: '',
        unitPrice: 1004,
        unitPriceIncludeTax: '',
        quantity: 1,
        unit: '',
        nsAmt: 1004,
        nsTaxAmt: 50,
        nsTotalAmt: 1054,
        nsLineSeq: 1,
        nsLine: 1,
        itemType: 'OthCharge',
        itemMemo: '',
        itemRateAfterTax: '',
        taxCode: { value: 118, text: '三收銀及電子發票' },
        taxRate: '5.00%',
        buyerTaxId: 24549210,
        tranType: 'Invoice',
        tranid: 'IV00000056569294',
        tranNum: 'CUSTINVC365490',
        tranInternalId: 3661843,
        itemDiscountAmt: '',
        itemDiscountCount: '',
        itemDisplayName: '商品一批(銷售)',
        taxType: {
          name: '1-應稅',
          value: '1',
          text: '應稅',
          csvValue: '應稅',
          taxCodes: { value: '118', text: '三收銀及電子發票' },
          id: '1'
        },
        gwSalesAmt: 1004,
        gwTaxExemptedSalesAmt: 0,
        gwTaxZeroSalesAmt: 0,
        gwTaxAmt: 50.2,
        gwTotalAmt: 1054.2,
        nsTaxExemptedSalesAmt: 0,
        nsTaxZeroSalesAmt: 0,
        salesAmt: 1004,
        taxAmt: 50,
        totalAmt: 1054,
        taxZeroSalesAmt: 0,
        taxExemptedSalesAmt: 0,
        lineSeq: 1
      }
    ]
  }
  var result = gwEguiBookService.updateLastEGuiNumber(eguiObj)
  log.debug({ title: 'result', details: result })
  log.debug({ title: 'Execution end' })
})
