require([
  'SuiteApps/com.gateweb.gwegui/gw_issue_egui_job/gw_allowance_controller',
], (gwAllowanceController) => {
  const creditMemoSearchResult = [
    {
      internalId: {
        value: 5,
        text: 5,
      },
      mainline: '*',
      trandate: '5/18/2021',
      subsidiary: {
        value: 3,
        text:
          'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
      },
      type: {
        value: 'CustCred',
        text: 'Credit Memo',
      },
      entity: {
        value: 16,
        text: '3 TestCompany',
      },
      tranid: 2,
      transactionnumber: 2,
      memomain: '',
      memo: '',
      amount: -1039.5,
      fxamount: -1039.5,
      grossamount: -1039.5,
      netamountnotax: -990,
      netamount: -1039.5,
      taxamount: '',
      taxtotal: -49.5,
      total: -1039.5,
      department: '',
      createdby: {
        value: 12,
        text: 'Sean Lin',
      },
      createdfrom: {
        value: 3,
        text: 'Invoice #1',
      },
      class: '',
      location: {
        value: 4,
        text: 'Taiwan : Taipei-Taipei',
      },
      itemtype: '',
      linesequencenumber: 0,
      line: 0,
      item: '',
      unitabbreviation: '',
      quantity: '',
      taxcode: '',
      rate: '',
      fxrate: '',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: 'TEST COMPANY TITLE',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: 24549210,
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: {
        value: 'applied',
        text: 'Fully Applied',
      },
      'rate.taxItem': '',
    },
    {
      internalId: {
        value: 5,
        text: 5,
      },
      mainline: ' ',
      trandate: '5/18/2021',
      subsidiary: {
        value: 3,
        text:
          'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
      },
      type: {
        value: 'CustCred',
        text: 'Credit Memo',
      },
      entity: {
        value: 16,
        text: '3 TestCompany',
      },
      tranid: 2,
      transactionnumber: 2,
      memomain: '',
      memo: '',
      amount: -990,
      fxamount: -990,
      grossamount: -990,
      netamountnotax: -990,
      netamount: -990,
      taxamount: -49.5,
      taxtotal: -49.5,
      total: -1039.5,
      department: '',
      createdby: {
        value: 12,
        text: 'Sean Lin',
      },
      createdfrom: {
        value: 3,
        text: 'Invoice #1',
      },
      class: '',
      location: {
        value: 4,
        text: 'Taiwan : Taipei-Taipei',
      },
      itemtype: 'InvtPart',
      linesequencenumber: 1,
      line: 1,
      item: {
        value: 9,
        text: 'GW Test Item 1',
      },
      unitabbreviation: '個',
      quantity: -1,
      taxcode: {
        value: 6,
        text: '應稅-5%',
      },
      rate: 990,
      fxrate: 990,
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: 'TEST COMPANY TITLE',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: 24549210,
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: {
        value: 'applied',
        text: 'Fully Applied',
      },
      'rate.taxItem': '5.00%',
    },
    {
      internalId: {
        value: 5,
        text: 5,
      },
      mainline: ' ',
      trandate: '5/18/2021',
      subsidiary: {
        value: 3,
        text:
          'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
      },
      type: {
        value: 'CustCred',
        text: 'Credit Memo',
      },
      entity: {
        value: 15,
        text:
          'Default Tax Agency TW : Default Tax Agency TW (3 - GW Test Subsidiary - Taipei) (20210426-115517)',
      },
      tranid: 2,
      transactionnumber: 2,
      memomain: '',
      memo: 'VAT',
      amount: -49.5,
      fxamount: -49.5,
      grossamount: -49.5,
      netamountnotax: -49.5,
      netamount: -49.5,
      taxamount: '',
      taxtotal: -49.5,
      total: -1039.5,
      department: '',
      createdby: {
        value: 12,
        text: 'Sean Lin',
      },
      createdfrom: {
        value: 3,
        text: 'Invoice #1',
      },
      class: '',
      location: {
        value: 4,
        text: 'Taiwan : Taipei-Taipei',
      },
      itemtype: 'TaxItem',
      linesequencenumber: 4,
      line: 4,
      item: {
        value: 6,
        text: '應稅-5%',
      },
      unitabbreviation: '',
      quantity: -1,
      taxcode: {
        value: 6,
        text: '應稅-5%',
      },
      rate: 5,
      fxrate: '5.00%',
      custcol_gw_item_unit_amt_inc_tax: '',
      custcol_gw_item_memo: '',
      custbody_gw_gui_date: '',
      custbody_gw_gui_tax_file_date: '',
      custbody_gw_lock_transaction: 'F',
      custbody_gw_gui_not_upload: 'F',
      custbody_gw_is_issue_egui: 'T',
      custbody_gw_allowance_num_start: '',
      custbody_gw_allowance_num_end: '',
      custbody_gw_customs_export_no: '',
      custbody_gw_customs_export_category: '',
      custbody_gw_gui_address: '',
      custbody_gw_gui_title: 'TEST COMPANY TITLE',
      custbody_gw_gui_num_start: '',
      custbody_gw_gui_num_end: '',
      custbody_gw_tax_id_number: 24549210,
      custbody_gw_customs_export_date: '',
      custbody_gw_egui_clearance_mark: '',
      custbody_gw_applicable_zero_tax: '',
      custbody_gw_gui_main_memo: '',
      custbody_gw_gui_sales_amt_tax_exempt: '',
      custbody_gw_gui_sales_amt: '',
      custbody_gw_gui_sales_amt_tax_zero: '',
      custbody_gw_gui_tax_amt: '',
      custbody_gw_creditmemo_deduction_list: '',
      custbody_gw_gui_donation_code: '',
      custbody_gw_gui_donation_mark: 'F',
      custbody_gw_gui_carrier_type: '',
      custbody_gw_gui_carrier_id_1: '',
      custbody_gw_gui_carrier_id_2: '',
      custbody_gw_gui_apply_period: '',
      custbody_gw_gui_format: '',
      custbody_gw_gui_class: '',
      custbody_gw_gui_department: '',
      statusref: {
        value: 'applied',
        text: 'Fully Applied',
      },
      'rate.taxItem': '5.00%',
    },
  ]

  var result = gwAllowanceController.issueAllowanceFromCm(
    creditMemoSearchResult,
    5
  )
  log.debug({ title: 'result', details: result })
  log.debug({ title: 'Execution end' })
})
