require(['SuiteApps/com.gateweb.gwegui/gw_issue_egui_job/gw_egui_service'], (
  gwEguiService
) => {
  const invoice = {
    internalId: { value: '3', text: '3' },
    mainline: '*',
    trandate: '4/27/2021',
    subsidiary: {
      value: '3',
      text:
        'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
    },
    type: {
      value: 'CustInvc',
      text: 'Invoice',
    },
    entity: {
      value: '16',
      text: '3 TestCompany',
    },
    tranid: '1',
    transactionnumber: '1',
    memomain: '',
    memo: '',
    amount: '3118.50',
    fxamount: '3118.50',
    grossamount: '3118.50',
    netamountnotax: '2970.00',
    netamount: '3118.50',
    taxamount: '',
    taxtotal: '148.50',
    total: '3118.50',
    department: '',
    createdby: {
      value: '12',
      text: 'Sean Lin',
    },
    createdfrom: '',
    class: '',
    location: {
      value: '4',
      text: 'Taiwan : Taipei-Taipei',
    },
    itemtype: '',
    linesequencenumber: '0',
    line: '0',
    item: '',
    unitabbreviation: '',
    quantity: '',
    taxcode: '',
    rate: '',
    fxrate: '',
    custcol_gw_item_unit_amt_inc_tax: '',
    custcol_gw_item_memo: '',
    custbody_gw_gui_date: '',
    custbody_gw_gui_tax_file_date: '',
    custbody_gw_lock_transaction: 'F',
    custbody_gw_gui_not_upload: 'F',
    custbody_gw_is_issue_egui: 'T',
    custbody_gw_allowance_num_start: '',
    custbody_gw_allowance_num_end: '',
    custbody_gw_customs_export_no: '',
    custbody_gw_customs_export_category: '',
    custbody_gw_gui_address: '',
    custbody_gw_gui_title: '',
    custbody_gw_gui_num_start: '',
    custbody_gw_gui_num_end: '',
    custbody_gw_tax_id_number: '24549210',
    custbody_gw_customs_export_date: '',
    custbody_gw_egui_clearance_mark: '',
    custbody_gw_applicable_zero_tax: '',
    custbody_gw_gui_main_memo: '',
    custbody_gw_gui_sales_amt_tax_exempt: '',
    custbody_gw_gui_sales_amt: '',
    custbody_gw_gui_sales_amt_tax_zero: '',
    custbody_gw_gui_tax_amt: '',
    custbody_gw_creditmemo_deduction_list: '',
    custbody_gw_gui_donation_code: '',
    custbody_gw_gui_donation_mark: 'F',
    custbody_gw_gui_carrier_type: '',
    custbody_gw_gui_carrier_id_1: '',
    custbody_gw_gui_carrier_id_2: '',
    custbody_gw_gui_apply_period: '',
    custbody_gw_gui_format: '',
    custbody_gw_gui_class: '',
    custbody_gw_gui_department: '',
    statusref: {
      value: 'open',
      text: 'Open',
    },
    'rate.taxItem': '',
    lines: [
      {
        internalId: { value: '3', text: '3' },
        mainline: ' ',
        trandate: '4/27/2021',
        subsidiary: {
          value: '3',
          text:
            'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
        },
        type: {
          value: 'CustInvc',
          text: 'Invoice',
        },
        entity: {
          value: '16',
          text: '3 TestCompany',
        },
        tranid: '1',
        transactionnumber: '1',
        memomain: '',
        memo: '',
        amount: '2970.00',
        fxamount: '2970.00',
        grossamount: '2970.00',
        netamountnotax: '2970.00',
        netamount: '2970.00',
        taxamount: '148.50',
        taxtotal: '148.50',
        total: '3118.50',
        department: '',
        createdby: {
          value: '12',
          text: 'Sean Lin',
        },
        createdfrom: '',
        class: '',
        location: {
          value: '4',
          text: 'Taiwan : Taipei-Taipei',
        },
        itemtype: 'InvtPart',
        linesequencenumber: '1',
        line: '1',
        item: {
          value: '9',
          text: 'GW Test Item 1',
        },
        unitabbreviation: '個',
        quantity: '3',
        taxcode: {
          value: '6',
          text: '應稅-5%',
        },
        rate: '990.00',
        fxrate: '990.00',
        custcol_gw_item_unit_amt_inc_tax: '',
        custcol_gw_item_memo: '',
        custbody_gw_gui_date: '',
        custbody_gw_gui_tax_file_date: '',
        custbody_gw_lock_transaction: 'F',
        custbody_gw_gui_not_upload: 'F',
        custbody_gw_is_issue_egui: 'T',
        custbody_gw_allowance_num_start: '',
        custbody_gw_allowance_num_end: '',
        custbody_gw_customs_export_no: '',
        custbody_gw_customs_export_category: '',
        custbody_gw_gui_address: '',
        custbody_gw_gui_title: '',
        custbody_gw_gui_num_start: '',
        custbody_gw_gui_num_end: '',
        custbody_gw_tax_id_number: '24549210',
        custbody_gw_customs_export_date: '',
        custbody_gw_egui_clearance_mark: '',
        custbody_gw_applicable_zero_tax: '',
        custbody_gw_gui_main_memo: '',
        custbody_gw_gui_sales_amt_tax_exempt: '',
        custbody_gw_gui_sales_amt: '',
        custbody_gw_gui_sales_amt_tax_zero: '',
        custbody_gw_gui_tax_amt: '',
        custbody_gw_creditmemo_deduction_list: '',
        custbody_gw_gui_donation_code: '',
        custbody_gw_gui_donation_mark: 'F',
        custbody_gw_gui_carrier_type: '',
        custbody_gw_gui_carrier_id_1: '',
        custbody_gw_gui_carrier_id_2: '',
        custbody_gw_gui_apply_period: '',
        custbody_gw_gui_format: '',
        custbody_gw_gui_class: '',
        custbody_gw_gui_department: '',
        statusref: {
          value: 'open',
          text: 'Open',
        },
        'rate.taxItem': '5.00%',
      },
    ],
    taxLines: [
      {
        internalId: { value: '3', text: '3' },
        mainline: ' ',
        trandate: '4/27/2021',
        subsidiary: {
          value: '3',
          text:
            'Parent Company : GATEWEB Test Company - 1 : GW Test Subsidiary - Taipei',
        },
        type: {
          value: 'CustInvc',
          text: 'Invoice',
        },
        entity: {
          value: '15',
          text:
            'Default Tax Agency TW : Default Tax Agency TW (3 - GW Test Subsidiary - Taipei) (20210426-115517)',
        },
        tranid: '1',
        transactionnumber: '1',
        memomain: '',
        memo: 'VAT',
        amount: '148.50',
        fxamount: '148.50',
        grossamount: '148.50',
        netamountnotax: '148.50',
        netamount: '148.50',
        taxamount: '',
        taxtotal: '148.50',
        total: '3118.50',
        department: '',
        createdby: {
          value: '12',
          text: 'Sean Lin',
        },
        createdfrom: '',
        class: '',
        location: {
          value: '4',
          text: 'Taiwan : Taipei-Taipei',
        },
        itemtype: 'TaxItem',
        linesequencenumber: '4',
        line: '5',
        item: {
          value: '6',
          text: '應稅-5%',
        },
        unitabbreviation: '',
        quantity: '1',
        taxcode: {
          value: '6',
          text: '應稅-5%',
        },
        rate: '5.00',
        fxrate: '5.00%',
        custcol_gw_item_unit_amt_inc_tax: '',
        custcol_gw_item_memo: '',
        custbody_gw_gui_date: '',
        custbody_gw_gui_tax_file_date: '',
        custbody_gw_lock_transaction: 'F',
        custbody_gw_gui_not_upload: 'F',
        custbody_gw_is_issue_egui: 'T',
        custbody_gw_allowance_num_start: '',
        custbody_gw_allowance_num_end: '',
        custbody_gw_customs_export_no: '',
        custbody_gw_customs_export_category: '',
        custbody_gw_gui_address: '',
        custbody_gw_gui_title: '',
        custbody_gw_gui_num_start: '',
        custbody_gw_gui_num_end: '',
        custbody_gw_tax_id_number: '24549210',
        custbody_gw_customs_export_date: '',
        custbody_gw_egui_clearance_mark: '',
        custbody_gw_applicable_zero_tax: '',
        custbody_gw_gui_main_memo: '',
        custbody_gw_gui_sales_amt_tax_exempt: '',
        custbody_gw_gui_sales_amt: '',
        custbody_gw_gui_sales_amt_tax_zero: '',
        custbody_gw_gui_tax_amt: '',
        custbody_gw_creditmemo_deduction_list: '',
        custbody_gw_gui_donation_code: '',
        custbody_gw_gui_donation_mark: 'F',
        custbody_gw_gui_carrier_type: '',
        custbody_gw_gui_carrier_id_1: '',
        custbody_gw_gui_carrier_id_2: '',
        custbody_gw_gui_apply_period: '',
        custbody_gw_gui_format: '',
        custbody_gw_gui_class: '',
        custbody_gw_gui_department: '',
        statusref: {
          value: 'open',
          text: 'Open',
        },
        'rate.taxItem': '5.00%',
      },
    ],
  }
  const eGuiService = new gwEguiService()
  var result = eGuiService.uploadEgui(1302)
  log.debug({ title: 'result', details: result })
  log.debug({ title: 'Execution end' })
})
